#pragma once
#ifndef __COLLISION_DEFINITIONS_H__
#define __COLLISION_DEFINITIONS_H__

#define WALL_COLLISION_BITMASK 0x0001
#define PADDLE_COLLISION_BITMASK 0x0002
#define DEATH_COLLISION_BITMASK 0x0003
#define HERO_BALL_COLLISION_BITMASK 0x0004
#define HERO_BODY_COLLISION_BITMASK 0x0005
#define MONSTER_BALL_COLLISION_BITMASK 0x0006
#define MONSTER_BODY_COLLISION_BITMASK 0x0007
#define NEUTRAL_BALL_COLLISION_BITMASK 0x0008
#define COIN_BALL_COLLISION_BITMASK 0x0009
#define NEUTRAL_COIN_BALL_COLLISION_BITMASK 0x0010

#define BOMB_RANGE_COLLISION_BITMASK 0x0011
#define BOMB_BODY_COLLISION_BITMASK 0x0012

#define DOOR_COLLISION_BITMASK 0x0013
#define SECRET_DOOR_COLLISION_BITMASK  0x0014

#define SINGLE_BRICK_COLLISION_BITMASK 0x0020
#define DOUBLE_BRICK_COLLISION_BITMASK 0x0021
#define SOLID_BRICK_COLLISION_BITMASK 0x0022
#define SINGLE_NEUTRAL_BRICK_COLLISION_BITMASK 0x0023

#define SKILL_FIRE_BALL_SPRITE_COLLISION_BITMASK 0x0030
#define SKILL_LIGHTNING_COLLISION_BITMASK 0x0031

#define MERCHANT_COLLISION_BITMASK 0x0040

#define DRAGON_BREATH_COLLISION_BITMASK 0x0050

#define MONSTER_ME_PADDLE 0x0060

#endif // __COLLISION_DEFINITIONS_H__
