#pragma once
#ifndef __SKILL_DEFINITIONS_H__
#define __SKILL_DEFINITIONS_H__

#define SKILL_START 1
#define SKILL_SIZE 3

#define SKILL_NONE 0
#define SKILL_FIRST_AID 1
#define SKILL_FIRE_BALL 2
#define SKILL_LIGHTNING 3

#define SKILL_FIRE_BALL_DAMAGE 10
#define SKILL_LIGHTNING_DAMAGE 5

#endif // __SKILL_DEFINITIONS_H__
