#pragma once
#ifndef __ZINDEX_DEFINITIONS_H__
#define __ZINDEX_DEFINITIONS_H__

#define ZINDEX_BG 1

#define ZINDEX_STATUS_BG 2
#define ZINDEX_STATUS_LABEL 3
#define ZINDEX_STATUS_BACK_HEART 3
#define ZINDEX_STATUS_FRONT_HEART 4
#define ZINDEX_STATUS_ETC 3

#define ZINDEX_STATUS_MAP_BG 3
#define ZINDEX_STATUS_MAP_ROOM 4
#define ZINDEX_STATUS_MAP_TYPE 5

#define ZINDEX_STATUS_SKILL 5
#define ZINDEX_STATUS_SKILL_FRAME 6
#define ZINDEX_STATUS_SKILL_IMAGE 7
#define ZINDEX_STATUS_SKILL_MAX_POINT 8
#define ZINDEX_STATUS_SKILL_CURRENT_POINT 9
#define ZINDEX_STATUS_SKILL_POINT_FRAME 10

#define ZINDEX_HELPERMAN_SPRITE 18

#define ZINDEX_HERO_SPRITE 20 
#define ZINDEX_HERO_WEAPON  19
#define ZINDEX_HERO_PADDLE 21
#define ZINDEX_HERO_BALL 23
#define ZINDEX_HERO_BOMB 23

#define ZINDEX_MONSTER_SPRITE 31
#define ZINDEX_MONSTER_BALL 23
#define ZINDEX_MONSTER_HP 24
#define ZINDEX_CHEST_SPRITE 24
#define ZINDEX_CHEST_GLOW 25
#define ZINDEX_CHEST_FRAME 26
#define ZINDEX_CHEST_ITEM 27

#define ZINDEX_BRICK_SPRITE 20
#define ZINDEX_ITEM_SPRITE 28
#define ZINDEX_CAGE_SPRITE 29

#define ZINDEX_ENDING_DOOR 32
#define ZINDEX_MOVE_DOOR 23

#define ZINDEX_EFFECT_BACK 18
#define ZINDEX_EFFECT_FRONT 35

#define ZINDEX_PAUSE_BG 50
#define ZINDEX_PAUSE_MENU 51
#define ZINDEX_PAUSE_UPPER_MENU 52

#define ZINDEX_CHARACTER_FRAME 40
#define ZINDEX_CHARACTER_LABEL 41
#define ZINDEX_CHARACTER_SPRITE 41
#define ZINDEX_CHARACTER_SHINING 41

#define ZINDEX_TUTORIAL_BTN 40
#define ZINDEX_TUTORIAL_SPRITE 41

#endif // __ZINDEX_DEFINITIONS_H__
